#!/bin/bash

INPUT="$1"
OUTPUT="$2"

if [ $# = 2 ]; then
    if [ -e "$INPUT" ]; then
        ./malice2asm "$INPUT" "$OUTPUT"
        
        if [ -e "$OUTPUT.asm" ]; then
            nasm -f elf "$OUTPUT.asm"
            
            if [ $? = 0 ]; then
                ld -o "$OUTPUT" "$OUTPUT.o"

                if [ $? = 0 ]; then
                    echo "Done."
                else
                    echo "Failed to link."
                    exit 1
                fi
                
                rm -f "$OUTPUT.o"
            else
                echo "Failed to assemble."
                exit 1
            fi
            
#            rm -f "$OUTPUT.asm"
        else
            echo "Failed to compile."
            exit 1
        fi
    else
        echo "Could not find file $INPUT."
        return 1;
    fi
else
    echo "Usage: ./compile input_file output_file"
fi
